force-app/main/default/objects/Product_Fee__c/Product_Fee__c.object-meta.xml
<CustomObject>
    <label>Product Fee</label>
    <nameField>
        <label>Product Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Fee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Fee__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <label>ATM Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Fee__c/fields/Card_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement__c</fullName>
    <label>Card Replacement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Fee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Fee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/productWrapper.cls
global class productWrapper {  // global class (was public)
    @AuraEnabled 
    global String product;      // global fields (was public)
    @AuraEnabled 
    global String country;
    @AuraEnabled 
    global Decimal monthlyFee;
    @AuraEnabled 
    global Decimal atmFee;
    @AuraEnabled 
    global Decimal cardReplacement;
    
    global productWrapper(Product_Fee__c fee) {  // global constructor
        this.product = fee.Product__c;
        this.country = fee.Country__c;
        this.monthlyFee = fee.Monthly_Fee__c;
        this.atmFee = fee.ATM_Fee__c;          //fee.ATM_Fee__c?.multiply(100);
        this.cardReplacement = fee.Card_Replacement__c;
    }
}